### PR TITLE
Downloads lib automatically

### PR DESCRIPTION
**Pull request by 19-ade**

### CODE REVIEW

**Comment by Titan1911** [comment]
I tried running the automated_download.py in my local machine but the line number 8, i.e.  
   ` reqs = subprocess.check_output([sys.executable, "-m", "pip", "show", str(package)])`
shows me this error:
```
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\hp\\anaconda3\\python.exe', '-m', 'pip', 'show', 'openpyxl']' returned non-zero exit status 2.
```
I tried running the code without this and it runs fine. So should I remove the line while merging or will you provide a solution to this?

**Comment by 19-ade** [comment]
Yes You can remove the line while merging it . This was just a boiler plate nothing else. Only the first line matters. However I will try and find why it is throwing this error. Thanks for letting me know.

**Comment by Titan1911** [comment]
One more thing, please can you make a pull request onto the `Attendance.py` file because I want a single file to do all the things.

**Comment by 19-ade** [comment]
Check Pull requests

**Pull request closed without merging**
